version: '3.8'

services:
  db:
    image: mysql:8.3.0
    container_name: mysql830
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul

  fastapiapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapiapp
    volumes:
      - .:/app
    expose:
      - "8000"


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapiapp
